services:
  - type: web
    name: dinner-planner-cadillac
    env: static
    staticPublishPath: client
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
